import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  "en": {
    "translation": {
      "Welcome_Message": "Welcome back",
      "Balance_Label": "Your available balance",
      "Send_Money_Button": "Send Money",
      "My_QR_Code_Button": "My QR Code",
      "Transfer_Card_Title": "Transfer",
      "Top_Up_Card_Title": "Top Up",
      "History_Card_Title": "History",
      "Transaction_History": "Transaction History",
      "recentPayments": "Recent Payments",
      "all_transactions": "View all your transactions",
      "Summary": "Summary",
      "Home": "Home",
      "report": "Report",
      "notify": "Notify",
      "profile": "Profile",
      "Total_Sent": "Total Sent",
      "Total_Received": "Total Received",
      "Profile_Settings": "Profile Settings",
      "account_information": "Manage your account information",
      "Update_Name": "Update Name",
      "Update_UPI": "Update UPI ID",
      "Update_Profile": "Update Profile",
      "Update_PIN": "Update PIN",
      "Current_pin": "Current Pin",
      "New_Pin": "New pin (6 digits)",
      "Conf_pin": "Confirm Pin",
      "Easy Offline Payment": "Easy Offline Payment",
      "Empowering Every Transaction, Even Without Internet": "Empowering Every Transaction, Even Without Internet",
      "Trusted by millions across rural India": "Trusted by millions across rural India",
      "Works Offline": "Works Offline",
      "No internet connection required for transactions": "No internet connection required for transactions",
      "Bank Grade Security": "Bank Grade Security",
      "Simple Interface": "Simple Interface",
      "Login to Account": "Login to Account",
      "Create Account": "Create Account",
      "Sign in to your account to continue": "Sign in to your account to continue",
      "UPI ID": "UPI ID",
      "Remember UPI ID": "Remember UPI ID",
      "Login": "Login",
      "Full Name": "Full Name",
      "Email": "Email",
      "Phone Number": "Phone Number",
      "Join millions of users across India": "Join millions of users across India",
      "Multilingual_Support": "Multilingual Support",
      "Language_Support_Description": "Available in 8+ Indian languages",
      "Advanced_Security": "Advanced encryption and security protocols",
      "Easy_Interface": "Simple and intuitive interface for everyone",
      "No_Internet_Required": "No internet connection needed for transactions",
      "Back": "Back",
      "Secure_Login": "Secure Login",
      "Enter_6_digit_PIN": "Enter 6-digit PIN",
      "Forgot_PIN": "Forgot PIN?",
      "Logging_in": "Logging in...",
      "Dont_have_account": "Don't have an account?",
      "Sign_Up": "Sign Up",
      "PIN": "PIN",
      "Create_Pin": "Create PIN",
      "6-digit_PIN": "Enter 6-digit PIN",
      "Confirm_6-digit_PIN": "Confirm 6-digit PIN",
      "blogs": "Blogs",
      "Financial_News": "Financial News",
      "Failed_to_fetch_news": "Failed to fetch news. Please try again later.",
      "No_News_Available": "No news articles available",
      "Check_Back_Later": "Please check back later for updates"
    }
  },
  "hi": {
    "translation": {
      "Welcome_Message": "वापसी पर स्वागत है",
      "Balance_Label": "आपकी उपलब्ध शेष राशि",
      "Send_Money_Button": "पैसे भेजें",
      "My_QR_Code_Button": "मेरा क्यूआर कोड",
      "Transfer_Card_Title": "ट्रांसफर",
      "Top_Up_Card_Title": "टॉप अप",
      "History_Card_Title": "इतिहास",
      "Transaction_History": "लेन-देन का इतिहास",
      "recentPayments": "हाल के भुगतान",
      "all_transactions": "अपने सभी लेन-देन देखें",
      "Summary": "सारांश",
      "Home": "होम",
      "report": "रिपोर्ट",
      "notify": "सूचित करें",
      "profile": "प्रोफ़ाइल",
      "Total_Sent": "कुल भेजा गया",
      "Total_Received": "कुल प्राप्त हुआ",
      "Profile_Settings": "प्रोफ़ाइल सेटिंग्स",
      "account_information": "अपनी खाता जानकारी प्रबंधित करें",
      "Update_Name": "नाम अपडेट करें",
      "Update_UPI": "यूपीआई आईडी अपडेट करें",
      "Update_Profile": "प्रोफ़ाइल अपडेट करें",
      "Update_PIN": "पिन अपडेट करें",
      "Current_pin": "वर्तमान पिन",
      "New_Pin": "नया पिन (6 अंक)",
      "Conf_pin": "पिन की पुष्टि करें",
      "Easy Offline Payment": "आसान ऑफलाइन भुगतान",
      "Empowering Every Transaction, Even Without Internet": "इंटरनेट के बिना भी, हर लेनदेन को सशक्त बनाना",
      "Trusted by millions across rural India": "ग्रामीण भारत में लाखों लोगों द्वारा विश्वसनीय",
      "Works Offline": "ऑफ़लाइन काम करता है",
      "No internet connection required for transactions": "लेन-देन के लिए कोई इंटरनेट कनेक्शन की आवश्यकता नहीं है",
      "Bank Grade Security": "बैंक ग्रेड सुरक्षा",
      "Simple Interface": "सरल इंटरफ़ेस",
      "Login to Account": "अकाउंट में लॉग इन करें",
      "Create Account": "खाता बनाएं",
      "Sign in to your account to continue": "जारी रखने के लिए अपने खाते में साइन इन करें",
      "UPI ID": "यूपीआई आईडी",
      "Remember UPI ID": "यूपीआई आईडी याद रखें",
      "Login": "लॉग इन करें",
      "Full Name": "पूरा नाम",
      "Email": "ईमेल",
      "Phone Number": "फ़ोन नंबर",
      "Join millions of users across India": "पूरे भारत में लाखों उपयोगकर्ताओं से जुड़ें",
      "Multilingual_Support": "बहुभाषी समर्थन",
      "Language_Support_Description": "8+ भारतीय भाषाओं में उपलब्ध",
      "Advanced_Security": "उन्नत एन्क्रिप्शन और सुरक्षा प्रोटोकॉल",
      "Easy_Interface": "सभी के लिए सरल और सहज इंटरफ़ेस",
      "No_Internet_Required": "लेन-देन के लिए इंटरनेट कनेक्शन की आवश्यकता नहीं",
      "Back": "वापस",
      "Secure_Login": "सुरक्षित लॉगिन",
      "Enter_6_digit_PIN": "6 अंकों का पिन दर्ज करें",
      "Forgot_PIN": "पिन भूल गए?",
      "Logging_in": "लॉग इन हो रहा है...",
      "Dont_have_account": "खाता नहीं है?",
      "Sign_Up": "साइन अप करें",
      "PIN": "पिन",
      "Create_Pin": "पिन बनाएं",
      "6-digit_PIN": "6 अंकों का पिन दर्ज करें",
      "Confirm_6-digit_PIN": "6 अंकों का पिन पुष्टि करें",
      "blogs": "ब्लॉग",
      "Financial_News": "वित्तीय समाचार",
      "Failed_to_fetch_news": "समाचार प्राप्त करने में विफल। कृपया बाद में पुनः प्रयास करें।",
      "No_News_Available": "कोई समाचार उपलब्ध नहीं है",
      "Check_Back_Later": "अपडेट के लिए बाद में फिर से देखें"
    }
  },
  "ml": {
    "translation": {
      "Welcome_Message": "വീണ്ടും സ്വാഗതം",
      "Balance_Label": "നിങ്ങളുടെ ലഭ്യമായ ബാലൻസ്",
      "Send_Money_Button": "പണം അയയ്ക്കുക",
      "My_QR_Code_Button": "എന്റെ ക്യുആർ കോഡ്",
      "Transfer_Card_Title": "ട്രാൻസ്ഫർ",
      "Top_Up_Card_Title": "ടോപ്പ് അപ്പ്",
      "History_Card_Title": "ചരിത്രം",
      "Transaction_History": "ഇടപാട് ചരിത്രം",
      "recentPayments": "സമീപകാല പേയ്‌മെന്റുകൾ",
      "all_transactions": "നിങ്ങളുടെ എല്ലാ ഇടപാടുകളും കാണുക",
      "Summary": "സംഗ്രഹം",
      "Home": "ഹോം",
      "report": "റിപ്പോർട്ട്",
      "notify": "അറിയിക്കുക",
      "profile": "പ്രൊഫൈൽ",
      "Total_Sent": "ആകെ അയച്ചത്",
      "Total_Received": "ആകെ ലഭിച്ചത്",
      "Profile_Settings": "പ്രൊഫൈൽ ക്രമീകരണങ്ങൾ",
      "account_information": "നിങ്ങളുടെ അക്കൗണ്ട് വിവരങ്ങൾ നിയന്ത്രിക്കുക",
      "Update_Name": "പേര് അപ്ഡേറ്റ് ചെയ്യുക",
      "Update_UPI": "യുപിഐ ഐഡി അപ്ഡേറ്റ് ചെയ്യുക",
      "Update_Profile": "പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്യുക",
      "Update_PIN": "പിൻ അപ്ഡേറ്റ് ചെയ്യുക",
      "Current_pin": "നിലവിലെ പിൻ",
      "New_Pin": "പുതിയ പിൻ (6 അക്കങ്ങൾ)",
      "Conf_pin": "പിൻ സ്ഥിരീകരിക്കുക",
      "Easy Offline Payment": "എളുപ്പമുള്ള ഓഫ്‌ലൈൻ പേയ്‌മെന്റ്",
      "Empowering Every Transaction, Even Without Internet": "ഇന്റർനെറ്റ് ഇല്ലാതെ പോലും എല്ലാ ഇടപാടുകളും ശാക്തീകരിക്കുന്നു",
      "Trusted by millions across rural India": "ഗ്രാമീണ ഇന്ത്യയിലുടനീളമുള്ള ദശലക്ഷക്കണക്കിന് ആളുകൾ വിശ്വസിക്കുന്നു",
      "Works Offline": "ഓഫ്‌ലൈനായി പ്രവർത്തിക്കുന്നു",
      "No internet connection required for transactions": "ഇടപാടുകൾക്ക് ഇന്റർനെറ്റ് കണക്ഷൻ ആവശ്യമില്ല",
      "Bank Grade Security": "ബാങ്ക് ഗ്രേഡ് സുരക്ഷ",
      "Simple Interface": "ലളിതമായ ഇന്റർഫേസ്",
      "Login to Account": "അക്കൗണ്ടിലേക്ക് ലോഗിൻ ചെയ്യുക",
      "Create Account": "അക്കൗണ്ട് ഉണ്ടാക്കുക",
      "Sign in to your account to continue": "തുടരുന്നതിന് നിങ്ങളുടെ അക്കൗണ്ടിലേക്ക് സൈൻ ഇൻ ചെയ്യുക",
      "UPI ID": "യുപിഐ ഐഡി",
      "Remember UPI ID": "യുപിഐ ഐഡി ഓർക്കുക",
      "Login": "ലോഗിൻ ചെയ്യുക",
      "Full Name": "മുഴുവൻ പേര്",
      "Email": "ഇമെയിൽ",
      "Phone Number": "ഫോൺ നമ്പർ",
      "Join millions of users across India": "ഇന്ത്യയിലുടനീളമുള്ള ദശലക്ഷക്കണക്കിന് ഉപയോക്താക്കളോടൊപ്പം ചേരുക",
      "Multilingual_Support": "ബഹുഭാഷാ പിന്തുണ",
      "Language_Support_Description": "8+ ഇന്ത്യൻ ഭാഷകളിൽ ലഭ്യമാണ്",
      "Advanced_Security": "ഉന്നത എൻക്രിപ്ഷൻ ಮತ್ತು സുരക്ഷാ പ്രോട്ടോക്കോളുകൾ",
      "Easy_Interface": "എല്ലാവർക്കും എളുപ്പത്തിൽ ഉപയോഗിക്കാവുന്ന ഇന്റർഫേസ്",
      "No_Internet_Required": "ഇടപാടുകൾക്ക് ഇന്റർനെറ്റ് കണക്ഷൻ ആവശ്യമില്ല",
      "Back": "മടങ്ങുക",
      "Secure_Login": "സുരക്ഷിതമായ ലോഗിൻ",
      "Enter_6_digit_PIN": "6 അക്ക പിൻ നമ്പർ നൽകുക",
      "Forgot_PIN": "പിൻ നമ്പർ മറന്നോ?",
      "Logging_in": "ലോഗിൻ ചെയ്യുന്നു...",
      "Dont_have_account": "അക്കൗണ്ട് ഇല്ലേ?",
      "Sign_Up": "സൈൻ അപ്പ് ചെയ്യുക",
      "PIN": "പിൻ",
      "Create_Pin": "പിൻ സൃഷ്ടിക്കുക",
      "6-digit_PIN": "6 അക്ക പിൻ നൽകുക",
      "Confirm_6-digit_PIN": "6 അക്ക പിൻ സ്ഥിരീകരിക്കുക",
      "blogs": "ബ്ലോഗുകൾ",
      "Financial_News": "Financial News",
      "Failed_to_fetch_news": "Failed to fetch news. Please try again later.",
      "No_News_Available": "No news articles available",
      "Check_Back_Later": "Please check back later for updates"
    }
  },
  "te": {
    "translation": {
      "Welcome_Message": "తిరిగి స్వాగతం",
      "Balance_Label": "మీ అందుబాటులో ఉన్న బ్యాలెన్స్",
      "Send_Money_Button": "డబ్బు పంపండి",
      "My_QR_Code_Button": "నా QR కోడ్",
      "Transfer_Card_Title": "బదిలీ",
      "Top_Up_Card_Title": "టాప్ అప్",
      "History_Card_Title": "చరిత్ర",
      "Transaction_History": "లావాదేవీల చరిత్ర",
      "recentPayments": "ఇటీవలి చెల్లింపులు",
      "all_transactions": "మీ అన్ని లావాదేవీలను వీక్షించండి",
      "Summary": "సారాంశం",
      "Home": "హోమ్",
      "report": "నివేదిక",
      "notify": "తెలియజేయండి",
      "profile": "ప్రొఫైల్",
      "Total_Sent": "మొత్తం పంపబడింది",
      "Total_Received": "మొత్తం స్వీకరించబడింది",
      "Profile_Settings": "ప్రొఫైల్ సెట్టింగ్‌లు",
      "account_information": "మీ ఖాతా సమాచారాన్ని నిర్వహించండి",
      "Update_Name": "పేరును నవీకరించండి",
      "Update_UPI": "UPI IDని నవీకరించండి",
      "Update_Profile": "ప్రొఫైల్‌ను నవీకరించండి",
      "Update_PIN": "పిన్‌ను నవీకరించండి",
      "Current_pin": "ప్రస్తుత పిన్",
      "New_Pin": "కొత్త పిన్ (6 అంకెలు)",
      "Conf_pin": "పిన్‌ను నిర్ధారించండి",
      "Easy Offline Payment": "సులభమైన ఆఫ్‌లైన్ చెల్లింపు",
      "Empowering Every Transaction, Even Without Internet": "ఇంటర్నెట్ లేకుండా కూడా ప్రతి లావాదేవీని శక్తివంతం చేస్తుంది",
      "Trusted by millions across rural India": "గ్రామీణ భారతదేశంలో లక్షలాది మంది విశ్వసించారు",
      "Works Offline": "ఆఫ్‌లైన్‌లో పనిచేస్తుంది",
      "No internet connection required for transactions": "లావాదేవీలకు ఇంటర్నెట్ కనెక్షన్ అవసరం లేదు",
      "Bank Grade Security": "బ్యాంక్ గ్రేడ్ భద్రత",
      "Simple Interface": "సాధారణ ఇంటర్‌ఫేస్",
      "Login to Account": "ఖాతాకు లాగిన్ చేయండి",
      "Create Account": "ఖాతాను సృష్టించండి",
      "Sign in to your account to continue": "కొనసాగించడానికి మీ ఖాతాకు సైన్ ఇన్ చేయండి",
      "UPI ID": "UPI ID",
      "Remember UPI ID": "UPI IDని గుర్తుంచుకోండి",
      "Login": "లాగిన్ చేయండి",
      "Full Name": "పూర్తి పేరు",
      "Email": "ఇమెయిల్",
      "Phone Number": "ఫోను నంబరు",
      "Join millions of users across India": "భారతదేశవ్యాప్తంగా లక్షలాది మంది వినియోగదారులతో చేరండి",
      "Multilingual_Support": "బహుభాషా మద్దతు",
      "Language_Support_Description": "8+ భారతీయ భాషల్లో అందుబాటులో ఉంది",
      "Advanced_Security": "అధిక శ్రేణి ఎన్‌క్రిప్షన్ మరియు భద్రతా ప్రోటోకాల్",
      "Easy_Interface": "అందరికీ సులభమైన మరియు స్పష్టమైన ఇంటర్‌ఫేస్",
      "No_Internet_Required": "లావాదేవీలకు ఇంటర్నెట్ కనెక్షన్ అవసరం లేదు",
      "Back": "తిరిగి",
      "Secure_Login": "భద్రమైన లాగిన్",
      "Enter_6_digit_PIN": "6 అంకెల పిన్ నమోదు చేయండి",
      "Forgot_PIN": "పిన్ మర్చిపోయారా?",
      "Logging_in": "లాగింగ్ ఇన్ అవుతోంది...",
      "Dont_have_account": "ఖాతా లేదు?",
      "Sign_Up": "సైన్ అప్ చేయండి",
      "PIN": "పిన్",
      "Create_Pin": "పిన్ సృష్టించండి",
      "6-digit_PIN": "6 అంకెల పిన్ నమోదు చేయండి",
      "Confirm_6-digit_PIN": "6 అంకెల పిన్ నిర్ధారించండి",
      "blogs": "బ్లాగులు",
      "Financial_News": "Financial News",
      "Failed_to_fetch_news": "Failed to fetch news. Please try again later.",
      "No_News_Available": "No news articles available",
      "Check_Back_Later": "Please check back later for updates"
    }
  },
  "ta": {
    "translation": {
      "Welcome_Message": "மீண்டும் வருக",
      "Balance_Label": "உங்கள் தற்போதைய இருப்பு",
      "Send_Money_Button": "பணம் அனுப்பு",
      "My_QR_Code_Button": "எனது QR குறியீடு",
      "Transfer_Card_Title": "பரிமாற்றம்",
      "Top_Up_Card_Title": "டாப் அப்",
      "History_Card_Title": "வரலாறு",
      "Transaction_History": "பரிவர்த்தனை வரலாறு",
      "recentPayments": "சமீபத்திய கொடுப்பனவுகள்",
      "all_transactions": "உங்கள் அனைத்து பரிவர்த்தனைகளையும் காண்க",
      "Summary": "சுருக்கம்",
      "Home": "முகப்பு",
      "report": "அறிக்கை",
      "notify": "அறிவி",
      "profile": "சுயவிவரம்",
      "Total_Sent": "மொத்தம் அனுப்பப்பட்டது",
      "Total_Received": "மொத்தம் பெறப்பட்டது",
      "Profile_Settings": "சுயவிவர அமைப்புகள்",
      "account_information": "உங்கள் கணக்கு தகவலை நிர்வகிக்கவும்",
      "Update_Name": "பெயரைப் புதுப்பிக்கவும்",
      "Update_UPI": "UPI ஐடியைப் புதுப்பிக்கவும்",
      "Update_Profile": "சுயவிவரத்தைப் புதுப்பிக்கவும்",
      "Update_PIN": "பின்னைப் புதுப்பிக்கவும்",
      "Current_pin": "தற்போதைய பின்",
      "New_Pin": "புதிய பின் (6 இலக்கங்கள்)",
      "Conf_pin": "பின்னை உறுதிப்படுத்தவும்",
      "Easy Offline Payment": "எளிதான ஆஃப்லைன் கட்டணம்",
      "Empowering Every Transaction, Even Without Internet": "இணையம் இல்லாவிட்டாலும் ஒவ்வொரு பரிவர்த்தனையையும் மேம்படுத்துகிறது",
      "Trusted by millions across rural India": "கிராமப்புற இந்தியாவில் மில்லியன் கணக்கானவர்கள் நம்புகிறார்கள்",
      "Works Offline": "ஆஃப்லைனில் வேலை செய்கிறது",
      "No internet connection required for transactions": "பரிவர்த்தனைகளுக்கு இணைய இணைப்பு தேவையில்லை",
      "Bank Grade Security": "வங்கி தர பாதுகாப்பு",
      "Simple Interface": "எளிய இடைமுகம்",
      "Login to Account": "கணக்கில் உள்நுழைக",
      "Create Account": "கணக்கை உருவாக்கு",
      "Sign in to your account to continue": "தொடர உங்கள் கணக்கில் உள்நுழைக",
      "UPI ID": "UPI ஐடி",
      "Remember UPI ID": "UPI ஐடியை நினைவில் கொள்க",
      "Login": "உள்நுழைக",
      "Full Name": "முழு பெயர்",
      "Email": "மின்னஞ்சல்",
      "Phone Number": "தொலைபேசி எண்",
      "Join millions of users across India": "இந்தியா முழுவதும் மில்லியன் கணக்கான பயனர்களுடன் சேரவும்",
      "Multilingual_Support": "பலமொழி ஆதரவு",
      "Language_Support_Description": "8+ இந்திய மொழிகளில் கிடைக்கிறது",
      "Advanced_Security": "மேம்பட்ட குறியாக்கம் மற்றும் பாதுகாப்பு நெறிமுறைகள்",
      "Easy_Interface": "எல்லோருக்கும் எளிமையான மற்றும் புரிந்துகொள்ள எளிதான இடைமுகம்",
      "No_Internet_Required": "பரிவர்த்தனைகளுக்கு இணைய இணைப்பு தேவையில்லை",
      "Back": "மீண்டும்",
      "Secure_Login": "பாதுகாப்பான உள்நுழைவு",
      "Enter_6_digit_PIN": "6 இலக்க பின் எண் உள்ளிடவும்",
      "Forgot_PIN": "பின் எண் மறந்துவிட்டீர்களா?",
      "Logging_in": "உள்நுழைகிறது...",
      "Dont_have_account": "கணக்கு இல்லை?",
      "Sign_Up": "புதிய கணக்கு உருவாக்கவும்",
      "PIN": "பின்",
      "Create_Pin": "பின் உருவாக்கவும்",
      "6-digit_PIN": "6 இலக்க பின்னை உள்ளிடவும்",
      "Confirm_6-digit_PIN": "6 இலக்க பின்னை உறுதிப்படுத்தவும்",
      "blogs": "பிளாக்குகள்",
      "Financial_News": "Financial News",
      "Failed_to_fetch_news": "Failed to fetch news. Please try again later.",
      "No_News_Available": "No news articles available",
      "Check_Back_Later": "Please check back later for updates"
    }
  },
  "gu": {
    "translation": {
      "Welcome_Message": "પાછા સ્વાગત છે",
      "Balance_Label": "તમારું ઉપલબ્ધ બેલેન્સ",
      "Send_Money_Button": "પૈસા મોકલો",
      "My_QR_Code_Button": "મારો ક્યુઆર કોડ",
      "Transfer_Card_Title": "ટ્રાન્સફર",
      "Top_Up_Card_Title": "ટોપ અપ",
      "History_Card_Title": "ઇતિહાસ",
      "Transaction_History": "વ્યવહાર ઇતિહાસ",
      "recentPayments": "તાજેતરની ચુકવણીઓ",
      "all_transactions": "તમારા બધા વ્યવહારો જુઓ",
      "Summary": "સારાંશ",
      "Home": "હોમ",
      "report": "રિપોર્ટ",
      "notify": "સૂચિત કરો",
      "profile": "પ્રોફાઇલ",
      "Total_Sent": "કુલ મોકલેલ",
      "Total_Received": "કુલ પ્રાપ્ત",
      "Profile_Settings": "પ્રોફાઇલ સેટિંગ્સ",
      "account_information": "તમારી એકાઉન્ટ માહિતી મેનેજ કરો",
      "Update_Name": "નામ અપડેટ કરો",
      "Update_UPI": "યુપીઆઈ આઈડી અપડેટ કરો",
      "Update_Profile": "પ્રોફાઇલ અપડેટ કરો",
      "Update_PIN": "પિન અપડેટ કરો",
      "Current_pin": "વર્તમાન પિન",
      "New_Pin": "નવો પિન (6 અંકો)",
      "Conf_pin": "પિનની પુષ્ટિ કરો",
      "Easy Offline Payment": "સરળ ઑફલાઇન ચુકવણી",
      "Empowering Every Transaction, Even Without Internet": "ઇન્ટરનેટ વિના પણ દરેક વ્યવહારને સશક્ત બનાવવું",
      "Trusted by millions across rural India": "ગ્રામીણ ભારતમાં લાખો લોકો દ્વારા વિશ્વસનીય",
      "Works Offline": "ઑફલાઇન કાર્ય કરે છે",
      "No internet connection required for transactions": "વ્યવહારો માટે કોઈ ઇન્ટરનેટ કનેક્શનની જરૂર નથી",
      "Bank Grade Security": "બેંક ગ્રેડ સુરક્ષા",
      "Simple Interface": "સરળ ઇન્ટરફેસ",
      "Login to Account": "એકાઉન્ટમાં લોગિન કરો",
      "Create Account": "એકાઉન્ટ બનાવો",
      "Sign in to your account to continue": "ચાલુ રાખવા માટે તમારા એકાઉન્ટમાં સાઇન ઇન કરો",
      "UPI ID": "યુપીઆઈ આઈડી",
      "Remember UPI ID": "યુપીઆઈ આઈડી યાદ રાખો",
      "Login": "લૉગિન કરો",
      "Full Name": "પૂરું નામ",
      "Email": "ઈમેલ",
      "Phone Number": "ફોન નંબર",
      "Join millions of users across India": "સમગ્ર ભારતમાં લાખો વપરાશકર્તાઓ સાથે જોડાઓ",
      "Multilingual_Support": "બહુભાષી સપોર્ટ",
      "Language_Support_Description": "8+ ભારતીય ભાષાઓમાં ઉપલબ્ધ",
      "Advanced_Security": "ઉન્નત એન્ક્રિપ્શન અને સુરક્ષા પ્રોટોકોલ",
      "Easy_Interface": "સરળ અને સુગમ ઇન્ટરફેસ",
      "No_Internet_Required": "વ્યવહારો માટે ઇન્ટરનેટ કનેક્શનની જરૂર નથી",
      "Back": "પાછા",
      "Secure_Login": "સુરક્ષિત લોગિન",
      "Enter_6_digit_PIN": "6 અંકનો પિન દાખલ કરો",
      "Forgot_PIN": "પિન ભૂલ્યા?",
      "Logging_in": "લોગિન થઈ રહ્યું છે...",
      "Dont_have_account": "ખાતું નથી?",
      "Sign_Up": "સાઇન અપ કરો",
      "PIN": "પિન",
      "Create_Pin": "પિન બનાવો",
      "6-digit_PIN": "6 અંકનો પિન દાખલ કરો",
      "Confirm_6-digit_PIN": "6 અંકનો પિન પુષ્ટિ કરો",
      "blogs": "બ્લોગ્સ",
      "Financial_News": "Financial News",
      "Failed_to_fetch_news": "Failed to fetch news. Please try again later.",
      "No_News_Available": "No news articles available",
      "Check_Back_Later": "Please check back later for updates"
    }
  },
  "pa": {
    "translation": {
      "Welcome_Message": "ਵਾਪਸ ਆਉਣ 'ਤੇ ਸੁਆਗਤ ਹੈ",
      "Balance_Label": "ਤੁਹਾਡਾ ਉਪਲਬਧ ਬਕਾਇਆ",
      "Send_Money_Button": "ਪੈਸੇ ਭੇਜੋ",
      "My_QR_Code_Button": "ਮੇਰਾ QR ਕੋਡ",
      "Transfer_Card_Title": "ਟ੍ਰਾਂਸਫਰ",
      "Top_Up_Card_Title": "ਟਾਪ ਅੱਪ",
      "History_Card_Title": "ਇਤਿਹਾਸ",
      "Transaction_History": "ਲੈਣ-ਦੇਣ ਦਾ ਇਤਿਹਾਸ",
      "recentPayments": "ਹਾਲੀਆ ਭੁਗਤਾਨ",
      "all_transactions": "ਆਪਣੇ ਸਾਰੇ ਲੈਣ-ਦੇਣ ਵੇਖੋ",
      "Summary": "ਸੰਖੇਪ",
      "Home": "ਹੋਮ",
      "report": "ਰਿਪੋਰਟ",
      "notify": "ਸੂਚਿਤ ਕਰੋ",
      "profile": "ਪ੍ਰੋਫਾਈਲ",
      "Total_Sent": "ਕੁੱਲ ਭੇਜਿਆ ਗਿਆ",
      "Total_Received": "ਕੁੱਲ ਪ੍ਰਾਪਤ ਹੋਇਆ",
      "Profile_Settings": "ਪ੍ਰੋਫਾਈਲ ਸੈਟਿੰਗਜ਼",
      "account_information": "ਆਪਣੀ ਖਾਤਾ ਜਾਣਕਾਰੀ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ",
      "Update_Name": "ਨਾਮ ਅੱਪਡੇਟ ਕਰੋ",
      "Update_UPI": "UPI ਆਈਡੀ ਅੱਪਡੇਟ ਕਰੋ",
      "Update_Profile": "ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਕਰੋ",
      "Update_PIN": "ਪਿੰਨ ਅੱਪਡੇਟ ਕਰੋ",
      "Current_pin": "ਮੌਜੂਦਾ ਪਿੰਨ",
      "New_Pin": "ਨਵਾਂ ਪਿੰਨ (6 ਅੰਕ)",
      "Conf_pin": "ਪਿੰਨ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
      "Easy Offline Payment": "ਆਸਾਨ ਔਫਲਾਈਨ ਭੁਗਤਾਨ",
      "Empowering Every Transaction, Even Without Internet": "ਇੰਟਰਨੈੱਟ ਤੋਂ ਬਿਨਾਂ ਵੀ ਹਰ ਲੈਣ-ਦੇਣ ਨੂੰ ਸ਼ਕਤੀ ਪ੍ਰਦਾਨ ਕਰਨਾ",
      "Trusted by millions across rural India": "ਪੇਂਡੂ ਭਾਰਤ ਵਿੱਚ ਲੱਖਾਂ ਲੋਕਾਂ ਦੁਆਰਾ ਭਰੋਸੇਯੋਗ",
      "Works Offline": "ਔਫਲਾਈਨ ਕੰਮ ਕਰਦਾ ਹੈ",
      "No internet connection required for transactions": "ਲੈਣ-ਦੇਣ ਲਈ ਕੋਈ ਇੰਟਰਨੈਟ ਕਨੈਕਸ਼ਨ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ",
      "Bank Grade Security": "ਬੈਂਕ ਗ੍ਰੇਡ ਸੁਰੱਖਿਆ",
      "Simple Interface": "ਸਧਾਰਨ ਇੰਟਰਫੇਸ",
      "Login to Account": "ਖਾਤੇ ਵਿੱਚ ਲਾਗਇਨ ਕਰੋ",
      "Create Account": "ਖਾਤਾ ਬਣਾਓ",
      "Sign in to your account to continue": "ਜਾਰੀ ਰੱਖਣ ਲਈ ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ",
      "UPI ID": "UPI ਆਈਡੀ",
      "Remember UPI ID": "UPI ਆਈਡੀ ਯਾਦ ਰੱਖੋ",
      "Login": "ਲਾਗਿਨ ਕਰੋ",
      "Full Name": "ਪੂਰਾ ਨਾਂਮ",
      "Email": "ਈ - ਮੇਲ",
      "Phone Number": "ਫੋਨ ਨੰਬਰ",
      "Join millions of users across India": "ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ ਲੱਖਾਂ ਉਪਭੋਗਤਾਵਾਂ ਨਾਲ ਜੁੜੋ",
      "Multilingual_Support": "ਬਹੁਭਾਸ਼ੀ ਸਹਾਇਤਾ",
      "Language_Support_Description": "8+ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਉਪਲਬਧ",
      "Advanced_Security": "ਉੱਚ ਗੁਣਵੱਤਾ ਵਾਲੀ ਐਨਕ੍ਰਿਪਸ਼ਨ ਅਤੇ ਸੁਰੱਖਿਆ ਪ੍ਰੋਟੋਕੋਲ",
      "Easy_Interface": "ਸਭ ਲਈ ਆਸਾਨ ਅਤੇ ਸਮਝਣ ਵਿੱਚ ਆਸਾਨ ਇੰਟਰਫੇਸ",
      "No_Internet_Required": "ਲੈਣ-ਦੇਣ ਲਈ ਇੰਟਰਨੈੱਟ ਕਨੈਕਸ਼ਨ ਦੀ ਲੋੜ ਨਹੀਂ",
      "Back": "ਵਾਪਸ",
      "Secure_Login": "ਸੁਰੱਖਿਅਤ ਲਾਗਿਨ",
      "Enter_6_digit_PIN": "6 ਅੰਕਾਂ ਦਾ ਪਿਨ ਦਰਜ ਕਰੋ",
      "Forgot_PIN": "ਪਿਨ ਭੁੱਲ ਗਏ?",
      "Logging_in": "ਲਾਗਿੰਗ ਇਨ...",
      "Dont_have_account": "ਖਾਤਾ ਨਹੀਂ ਹੈ?",
      "Sign_Up": "ਸਾਈਨ ਅਪ ਕਰੋ",
      "PIN": "ਪਿਨ",
      "Create_Pin": "ਪਿੰਨ ਬਣਾਓ",
      "6-digit_PIN": "6 ਅੰਕਾਂ ਦਾ ਪਿੰਨ ਦਰਜ ਕਰੋ",
      "Confirm_6-digit_PIN": "6 ਅੰਕਾਂ ਦਾ ਪਿੰਨ ਪੁਸ਼ਟੀ ਕਰੋ",
      "blogs": "ਬਲੌਗਸ",
      "Financial_News": "ਵਿੱਤੀ ਖਬਰਾਂ",
      "Failed_to_fetch_news": "ਖਬਰਾਂ ਪ੍ਰਾਪਤ ਕਰਨ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਬਾਅਦ ਵਿੱਚ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
      "No_News_Available": "ਕੋਈ ਖਬਰਾਂ ਦੇ ਲੇਖ ਉਪਲਬਧ ਨਹੀਂ ਹਨ",
      "Check_Back_Later": "ਕਿਰਪਾ ਕਰਕੇ ਬਾਅਦ ਵਿੱਚ ਅਪਡੇਟ ਲਈ ਫਿਰ ਤੋਂ ਚੈੱਕ ਕਰੋ"
    }
  },
  "mr": {
    "translation": {
      "Welcome_Message": "परत स्वागत आहे",
      "Balance_Label": "तुमची उपलब्ध शिल्लक",
      "Send_Money_Button": "पैसे पाठवा",
      "My_QR_Code_Button": "माझा क्यूआर कोड",
      "Transfer_Card_Title": "हस्तांतरण",
      "Top_Up_Card_Title": "टॉप अप",
      "History_Card_Title": "इतिहास",
      "Transaction_History": "व्यवहार इतिहास",
      "recentPayments": "अलीकडील पेमेंट",
      "all_transactions": "तुमचे सर्व व्यवहार पहा",
      "Summary": "सारांश",
      "Home": "होम",
      "report": "अहवाल",
      "notify": "सूचित करा",
      "profile": "प्रोफाइल",
      "Total_Sent": "एकूण पाठवलेले",
      "Total_Received": "एकूण प्राप्त",
      "Profile_Settings": "प्रोफाइल सेटिंग्ज",
      "account_information": "तुमची खाते माहिती व्यवस्थापित करा",
      "Update_Name": "नाव अपडेट करा",
      "Update_UPI": "UPI आयडी अपडेट करा",
      "Update_Profile": "प्रोफाइल अपडेट करा",
      "Update_PIN": "पिन अपडेट करा",
      "Current_pin": "सध्याचा पिन",
      "New_Pin": "नवीन पिन (6 अंक)",
      "Conf_pin": "पिनची पुष्टी करा",
      "Easy Offline Payment": "सोपे ऑफलाइन पेमेंट",
      "Empowering Every Transaction, Even Without Internet": "इंटरनेटशिवायही प्रत्येक व्यवहाराला सक्षम बनवणे",
      "Trusted by millions across rural India": "ग्रामीण भारतातील लाखो लोकांचा विश्वास",
      "Works Offline": "ऑफलाइन कार्य करते",
      "No internet connection required for transactions": "व्यवहारांसाठी इंटरनेट कनेक्शनची आवश्यकता नाही",
      "Bank Grade Security": " बँक ग्रेड सुरक्षा",
      "Simple Interface": "साधा इंटरफेस",
      "Login to Account": "खात्यात लॉगिन करा",
      "Create Account": "खाते तयार करा",
      "Sign in to your account to continue": "सुरू ठेवण्यासाठी तुमच्या खात्यात साइन इन करा",
      "UPI ID": "UPI आयडी",
      "Remember UPI ID": "UPI आयडी लक्षात ठेवा",
      "Login": "लॉगिन करा",
      "Full Name": "पूर्ण नाव",
      "Email": "ईमेल",
      "Phone Number": "फोन नंबर",
      "Join millions of users across India": "भारतभरातील लाखो वापरकर्त्यांमध्ये सामील व्हा",
      "Multilingual_Support": "बहुभाषी समर्थन",
      "Language_Support_Description": "8+ भारतीय भाषांमध्ये उपलब्ध",
      "Advanced_Security": "उन्नत एन्क्रिप्शन आणि सुरक्षा प्रोटोकॉल",
      "Easy_Interface": "सर्वांसाठी सोपा आणि समजण्यास सोपा इंटरफेस",
      "No_Internet_Required": "व्यवहारांसाठी इंटरनेट कनेक्शनची आवश्यकता नाही",
      "Back": "परत",
      "Secure_Login": "सुरक्षित लॉगिन",
      "Enter_6_digit_PIN": "6-अंक पिन प्रविष्ट करा",
      "Forgot_PIN": "पिन विसरलात का?",
      "Logging_in": "लॉगिन होत आहे...",
      "Dont_have_account": "खात नाही का?",
      "Sign_Up": "साइन अप करा",
      "PIN": "पिन",
      "Create_Pin": "पिन तयार करा",
      "6-digit_PIN": "6 अंकी пин टाका",
      "Confirm_6-digit_PIN": "6 अंकी пिन पुष्टी करा",
      "blogs": "ब्लॉग",
      "Financial_News": "Financial News",
      "Failed_to_fetch_news": "Failed to fetch news. Please try again later.",
      "No_News_Available": "No news articles available",
      "Check_Back_Later": "Please check back later for updates"
    }
  }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: localStorage.getItem('language') || "en", // use persisted language or fallback to "en"
    fallbackLng: "en",
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
