import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  "en": {
    "translation": {
      "Welcome_Message": "Welcome back",
      "Balance_Label": "Your available balance",
      "Send_Money_Button": "Send Money",
      "My_QR_Code_Button": "My QR Code",
      "Transfer_Card_Title": "Transfer",
      "Top_Up_Card_Title": "Top Up",
      "History_Card_Title": "History",
      "Transaction_History": "Transaction History",
      "recentPayments": "Recent Payments",
      "all_transactions": "View all your transactions",
      "Summary": "Summary",
      "Home": "Home",
      "report": "Report",
      "notify": "Notify",
      "profile": "Profile",
      "Total_Sent": "Total Sent",
      "Total_Received": "Total Received",
      "Profile_Settings": "Profile Settings",
      "account_information": "Manage your account information",
      "Update_Name": "Update Name",
      "Update_UPI": "Update UPI ID",
      "Update_Profile": "Update Profile",
      "Update_PIN": "Update PIN",
      "Current_pin": "Current Pin",
      "New_Pin": "New pin (6 digits)",
      "Conf_pin": "Confirm Pin"
    }
  },
  "hi": {
    "translation": {
      "Welcome_Message": "वापसी पर स्वागत है",
      "Balance_Label": "आपकी उपलब्ध शेष राशि",
      "Send_Money_Button": "पैसे भेजें",
      "My_QR_Code_Button": "मेरा क्यूआर कोड",
      "Transfer_Card_Title": "ट्रांसफर",
      "Top_Up_Card_Title": "टॉप अप",
      "History_Card_Title": "इतिहास",
      "Transaction_History": "लेन-देन का इतिहास",
      "recentPayments": "हाल के भुगतान",
      "all_transactions": "अपने सभी लेन-देन देखें",
      "Summary": "सारांश",
      "Home": "होम",
      "report": "रिपोर्ट",
      "notify": "सूचित करें",
      "profile": "प्रोफ़ाइल",
      "Total_Sent": "कुल भेजा गया",
      "Total_Received": "कुल प्राप्त हुआ",
      "Profile_Settings": "प्रोफ़ाइल सेटिंग्स",
      "account_information": "अपनी खाता जानकारी प्रबंधित करें",
      "Update_Name": "नाम अपडेट करें",
      "Update_UPI": "यूपीआई आईडी अपडेट करें",
      "Update_Profile": "प्रोफ़ाइल अपडेट करें",
      "Update_PIN": "पिन अपडेट करें",
      "Current_pin": "वर्तमान पिन",
      "New_Pin": "नया पिन (6 अंक)",
      "Conf_pin": "पिन की पुष्टि करें"
    }
  },
  "ml": {
    "translation": {
      "Welcome_Message": "വീണ്ടും സ്വാഗതം",
      "Balance_Label": "നിങ്ങളുടെ ലഭ്യമായ ബാലൻസ്",
      "Send_Money_Button": "പണം അയയ്ക്കുക",
      "My_QR_Code_Button": "എന്റെ ക്യുആർ കോഡ്",
      "Transfer_Card_Title": "ട്രാൻസ്ഫർ",
      "Top_Up_Card_Title": "ടോപ്പ് അപ്പ്",
      "History_Card_Title": "ചരിത്രം",
      "Transaction_History": "ഇടപാട് ചരിത്രം",
      "recentPayments": "സമീപകാല പേയ്‌മെന്റുകൾ",
      "all_transactions": "നിങ്ങളുടെ എല്ലാ ഇടപാടുകളും കാണുക",
      "Summary": "സംഗ്രഹം",
      "Home": "ഹോം",
      "report": "റിപ്പോർട്ട്",
      "notify": "അറിയിക്കുക",
      "profile": "പ്രൊഫൈൽ",
      "Total_Sent": "ആകെ അയച്ചത്",
      "Total_Received": "ആകെ ലഭിച്ചത്",
      "Profile_Settings": "പ്രൊഫൈൽ ക്രമീകരണങ്ങൾ",
      "account_information": "നിങ്ങളുടെ അക്കൗണ്ട് വിവരങ്ങൾ നിയന്ത്രിക്കുക",
      "Update_Name": "പേര് അപ്ഡേറ്റ് ചെയ്യുക",
      "Update_UPI": "യുപിഐ ഐഡി അപ്ഡേറ്റ് ചെയ്യുക",
      "Update_Profile": "പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്യുക",
      "Update_PIN": "പിൻ അപ്ഡേറ്റ് ചെയ്യുക",
      "Current_pin": "നിലവിലെ പിൻ",
      "New_Pin": "പുതിയ പിൻ (6 അക്കങ്ങൾ)",
      "Conf_pin": "പിൻ സ്ഥിരീകരിക്കുക"
    }
  },
  "te": {
    "translation": {
      "Welcome_Message": "తిరిగి స్వాగతం",
      "Balance_Label": "మీ అందుబాటులో ఉన్న బ్యాలెన్స్",
      "Send_Money_Button": "డబ్బు పంపండి",
      "My_QR_Code_Button": "నా QR కోడ్",
      "Transfer_Card_Title": "బదిలీ",
      "Top_Up_Card_Title": "టాప్ అప్",
      "History_Card_Title": "చరిత్ర",
      "Transaction_History": "లావాదేవీల చరిత్ర",
      "recentPayments": "ఇటీవలి చెల్లింపులు",
      "all_transactions": "మీ అన్ని లావాదేవీలను వీక్షించండి",
      "Summary": "సారాంశం",
      "Home": "హోమ్",
      "report": "నివేదిక",
      "notify": "తెలియజేయండి",
      "profile": "ప్రొఫైల్",
      "Total_Sent": "మొత్తం పంపబడింది",
      "Total_Received": "మొత్తం స్వీకరించబడింది",
      "Profile_Settings": "ప్రొఫైల్ సెట్టింగ్‌లు",
      "account_information": "మీ ఖాతా సమాచారాన్ని నిర్వహించండి",
      "Update_Name": "పేరును నవీకరించండి",
      "Update_UPI": "UPI IDని నవీకరించండి",
      "Update_Profile": "ప్రొఫైల్‌ను నవీకరించండి",
      "Update_PIN": "పిన్‌ను నవీకరించండి",
      "Current_pin": "ప్రస్తుత పిన్",
      "New_Pin": "కొత్త పిన్ (6 అంకెలు)",
      "Conf_pin": "పిన్‌ను నిర్ధారించండి"
    }
  },
  "ta": {
    "translation": {
      "Welcome_Message": "மீண்டும் வருக",
      "Balance_Label": "உங்கள் தற்போதைய இருப்பு",
      "Send_Money_Button": "பணம் அனுப்பு",
      "My_QR_Code_Button": "எனது QR குறியீடு",
      "Transfer_Card_Title": "பரிமாற்றம்",
      "Top_Up_Card_Title": "டாப் அப்",
      "History_Card_Title": "வரலாறு",
      "Transaction_History": "பரிவர்த்தனை வரலாறு",
      "recentPayments": "சமீபத்திய கொடுப்பனவுகள்",
      "all_transactions": "உங்கள் அனைத்து பரிவர்த்தனைகளையும் காண்க",
      "Summary": "சுருக்கம்",
      "Home": "முகப்பு",
      "report": "அறிக்கை",
      "notify": "அறிவி",
      "profile": "சுயவிவரம்",
      "Total_Sent": "மொத்தம் அனுப்பப்பட்டது",
      "Total_Received": "மொத்தம் பெறப்பட்டது",
      "Profile_Settings": "சுயவிவர அமைப்புகள்",
      "account_information": "உங்கள் கணக்கு தகவலை நிர்வகிக்கவும்",
      "Update_Name": "பெயரைப் புதுப்பிக்கவும்",
      "Update_UPI": "UPI ஐடியைப் புதுப்பிக்கவும்",
      "Update_Profile": "சுயவிவரத்தைப் புதுப்பிக்கவும்",
      "Update_PIN": "பின்னைப் புதுப்பிக்கவும்",
      "Current_pin": "தற்போதைய பின்",
      "New_Pin": "புதிய பின் (6 இலக்கங்கள்)",
      "Conf_pin": "பின்னை உறுதிப்படுத்தவும்"
    }
  },
  "gu": {
    "translation": {
      "Welcome_Message": "પાછા સ્વાગત છે",
      "Balance_Label": "તમારું ઉપલબ્ધ બેલેન્સ",
      "Send_Money_Button": "પૈસા મોકલો",
      "My_QR_Code_Button": "મારો ક્યુઆર કોડ",
      "Transfer_Card_Title": "ટ્રાન્સફર",
      "Top_Up_Card_Title": "ટોપ અપ",
      "History_Card_Title": "ઇતિહાસ",
      "Transaction_History": "વ્યવહાર ઇતિહાસ",
      "recentPayments": "તાજેતરની ચુકવણીઓ",
      "all_transactions": "તમારા બધા વ્યવહારો જુઓ",
      "Summary": "સારાંશ",
      "Home": "હોમ",
      "report": "રિપોર્ટ",
      "notify": "સૂચિત કરો",
      "profile": "પ્રોફાઇલ",
      "Total_Sent": "કુલ મોકલેલ",
      "Total_Received": "કુલ પ્રાપ્ત",
      "Profile_Settings": "પ્રોફાઇલ સેટિંગ્સ",
      "account_information": "તમારી એકાઉન્ટ માહિતી મેનેજ કરો",
      "Update_Name": "નામ અપડેટ કરો",
      "Update_UPI": "યુપીઆઈ આઈડી અપડેટ કરો",
      "Update_Profile": "પ્રોફાઇલ અપડેટ કરો",
      "Update_PIN": "પિન અપડેટ કરો",
      "Current_pin": "વર્તમાન પિન",
      "New_Pin": "નવો પિન (6 અંકો)",
      "Conf_pin": "પિનની પુષ્ટિ કરો"
    }
  },
  "pa": {
    "translation": {
      "Welcome_Message": "ਵਾਪਸ ਆਉਣ 'ਤੇ ਸੁਆਗਤ ਹੈ",
      "Balance_Label": "ਤੁਹਾਡਾ ਉਪਲਬਧ ਬਕਾਇਆ",
      "Send_Money_Button": "ਪੈਸੇ ਭੇਜੋ",
      "My_QR_Code_Button": "ਮੇਰਾ QR ਕੋਡ",
      "Transfer_Card_Title": "ਟ੍ਰਾਂਸਫਰ",
      "Top_Up_Card_Title": "ਟਾਪ ਅੱਪ",
      "History_Card_Title": "ਇਤਿਹਾਸ",
      "Transaction_History": "ਲੈਣ-ਦੇਣ ਦਾ ਇਤਿਹਾਸ",
      "recentPayments": "ਹਾਲੀਆ ਭੁਗਤਾਨ",
      "all_transactions": "ਆਪਣੇ ਸਾਰੇ ਲੈਣ-ਦੇਣ ਵੇਖੋ",
      "Summary": "ਸੰਖੇਪ",
      "Home": "ਹੋਮ",
      "report": "ਰਿਪੋਰਟ",
      "notify": "ਸੂਚਿਤ ਕਰੋ",
      "profile": "ਪ੍ਰੋਫਾਈਲ",
      "Total_Sent": "ਕੁੱਲ ਭੇਜਿਆ ਗਿਆ",
      "Total_Received": "ਕੁੱਲ ਪ੍ਰਾਪਤ ਹੋਇਆ",
      "Profile_Settings": "ਪ੍ਰੋਫਾਈਲ ਸੈਟਿੰਗਜ਼",
      "account_information": "ਆਪਣੀ ਖਾਤਾ ਜਾਣਕਾਰੀ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ",
      "Update_Name": "ਨਾਮ ਅੱਪਡੇਟ ਕਰੋ",
      "Update_UPI": "UPI ਆਈਡੀ ਅੱਪਡੇਟ ਕਰੋ",
      "Update_Profile": "ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਕਰੋ",
      "Update_PIN": "ਪਿੰਨ ਅੱਪਡੇਟ ਕਰੋ",
      "Current_pin": "ਮੌਜੂਦਾ ਪਿੰਨ",
      "New_Pin": "ਨਵਾਂ ਪਿੰਨ (6 ਅੰਕ)",
      "Conf_pin": "ਪਿੰਨ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ"
    }
  },
  "mr": {
    "translation": {
      "Welcome_Message": "परत स्वागत आहे",
      "Balance_Label": "तुमची उपलब्ध शिल्लक",
      "Send_Money_Button": "पैसे पाठवा",
      "My_QR_Code_Button": "माझा क्यूआर कोड",
      "Transfer_Card_Title": "हस्तांतरण",
      "Top_Up_Card_Title": "टॉप અપ",
      "History_Card_Title": "इतिहास",
      "Transaction_History": "व्यवहार इतिहास",
      "recentPayments": "अलीकडील पेमेंट",
      "all_transactions": "तुमचे सर्व व्यवहार पहा",
      "Summary": "सारांश",
      "Home": "होम",
      "report": "अहवाल",
      "notify": "सूचित करा",
      "profile": "प्रोफाइल",
      "Total_Sent": "एकूण पाठवलेले",
      "Total_Received": "एकूण प्राप्त",
      "Profile_Settings": "प्रोफाइल सेटिंग्ज",
      "account_information": "तुमची खाते माहिती व्यवस्थापित करा",
      "Update_Name": "नाव अपडेट करा",
      "Update_UPI": "UPI आयडी अपडेट करा",
      "Update_Profile": "प्रोफाइल अपडेट करा",
      "Update_PIN": "पिन अपडेट करा",
      "Current_pin": "सध्याचा पिन",
      "New_Pin": "नवीन पिन (6 अंक)",
      "Conf_pin": "पिनची पुष्टी करा"
    }
  }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: localStorage.getItem('language') || "en", // use persisted language or fallback to "en"
    fallbackLng: "en",
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
