version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_OFl7CP9tLdfj
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=paysevaservice@gmail.com
      - SPRING_MAIL_PASSWORD=ntds rwvq qlit hryc
      - TWILIO_ACCOUNT_SID=your_account_sid_here
      - TWILIO_AUTH_TOKEN=your_auth_token_here
      - TWILIO_PHONE_NUMBER=your_twilio_phone_number_here
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - offline-upi-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=neondb
      - POSTGRES_USER=neondb_owner
      - POSTGRES_PASSWORD=npg_OFl7CP9tLdfj
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - offline-upi-network

volumes:
  postgres-data:

networks:
  offline-upi-network:
    driver: bridge 